# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otter/gui/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtterMainWindow(object):
    def setupUi(self, OtterMainWindow):
        OtterMainWindow.setObjectName("OtterMainWindow")
        OtterMainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        OtterMainWindow.resize(762, 479)
        self.centralwidget = QtWidgets.QWidget(OtterMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        OtterMainWindow.setCentralWidget(self.centralwidget)
        self.action_quit = QtWidgets.QAction(OtterMainWindow)
        self.action_quit.setObjectName("action_quit")

        self.retranslateUi(OtterMainWindow)
        QtCore.QMetaObject.connectSlotsByName(OtterMainWindow)

    def retranslateUi(self, OtterMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OtterMainWindow.setWindowTitle(_translate("OtterMainWindow", "MainWindow"))
        self.action_quit.setText(_translate("OtterMainWindow", "Quit"))
